@restapi_c_HostAddress = http://localhost:5038

### 获取北京天气
GET {{restapi_c_HostAddress}}/weather/beijing
Accept: application/json

### 获取上海天气
GET {{restapi_c_HostAddress}}/weather/shanghai
Accept: application/json

### 获取东京天气
GET {{restapi_c_HostAddress}}/weather/tokyo
Accept: application/json